const mongoose = require("mongoose");
var Schema = mongoose.Schema;

let busesSchema = new Schema({
    partnerId:{
        type:mongoose.Types.ObjectId,
        ref:'partner'
    },
    busName:{
        type:String,
        ref:''
    },
    busNumber:{
        type:String,
        default:null,
        required:true
    },
    is_active:{
        type:Boolean,
        default:true,
        required:false
    },
    busRoadMap:{
        journeyForm:{
            type:String,
            default:null,
            required:true
        },
        journeyTo:{
            type:String,
            default:'one way',
            required:true
        },
        journeyFare:{
            type:Number,
            default:null,
            required:false
        },
        viaRoot:[
            {
                rootName:{
                    type:String,
                    default:null,
                    required:false
                },
                journeyFormRootFare :{  
                    type:Number,
                    default:null,
                    required:false
                },
                journeyToRootFare:{
                    type:Number,
                    default:null,
                    required:false
                }
            }
        ]
    },
    busTiming:{
        departureTime:{
            type:String,
            default:''
        },
        arrivalTime:{
            type:String,
            default:''
        },
    },
    busFeature:{
        noOfSeat:{
            type:Number,
            default:0
        },
        busType:{
            type:String,
            default:''
        },
        acType:{
            type:String,
            default:"Non-Ac"
        },
        multimediaType:{
            type:String,
            default:''
        }
    },
    busDescription:{
        type:String,
        default:''
    },
    busImages:{
        front_side:{
            type:String,
            default:null,
            required:true
        },
        left_side:{
            type:String,
            default:null,
            required:true
        },
        right_side:{
            type:String,
            default:null,
            required:true
        },
        back_side:{
            type:String,
            default:null,
            required:true
        },
        driver_cabin:{
            type:String,
            default:null,
            required:true
        },
        entire_inside:{
            type:String,
            default:null,
            required:true
        }
    },
    seatTemplate:{
        type:String,
        default:null,
        required:false
    },
    drivers:[
        {
            name:{
                type:String,
                default:'',
            },
            mobile:{
                type:String,
                default:'',
                require:true
            },
            email:{
                type:String,
                default :'',
                required : false
            },
            password:{
                type:String,
                default:'',
                required : true
            },
            streetAddress:{
                type:String,
                default:'',
                required:false
            },
            zipCode:{
                type:String,
                default:'',
                required:false
            },
            city:{
                type:String,
                default:'',
                required:false
            },
            is_active:{
                type:Boolean,
                default:true,
                required:false
            },
            currentPosition:{
                lat:{
                    type:String,
                    default:null,
                    required : false
                },
                long:{
                    type:String,
                    default:null,
                    required:false
                }
            },
            assignDate:{
                type:Date,
                default:Date.now(),
                required:false
            }
        }
    ],
    conductors:[
        {   name:{
                type:String,
                default:''
            },
            mobile:{
                type:String,
                default:''
            },
            email:{
                type:String,
                default :'',
                required : false
            },
            password:{
                type:String,
                default:'',
                required : true
            },
            streetAddress:{
                type:String,
                default:'',
                required:false
            },
            zipCode:{
                type:String,
                default:'',
                required:false
            },
            city:{
                type:String,
                default:'',
                required:false
            },
            is_active:{
                type:Boolean,
                default:true,
                required:false
            },
            currentPosition:{
                lat:{
                    type:String,
                    default:null,
                    required : false
                },
                long:{
                    type:String,
                    default:null,
                    required:false
                }
            },
            assignDate:{
                type:Date,
                default:Date.now(),
                required:false
            }
        }
    ]
},{
    timestamps:true
})

module.exports = mongoose.model("buses",busesSchema);