const mongoose = require("mongoose");
var Schema = mongoose.Schema;

let busesSchema = new Schema({
    partnetId:{
        type:mongoose.Types.ObjectId,
        ref:'partner'
    },
    busStatus:{
        type:String,
        default:'active'
    },
    busName:{
        type:String,
        ref:''
    },
    busNumber:{
        type:String,
        default:null,
        required:true
    },
    busRoadMap:{
        journeyForm:{
            type:String,
            default:null,
            required:true
        },
        journeyTo:{
            type:String,
            default:'one way',
            required:true
        },
        viaRoot1:{
            type:String,
            default:''
        },
        viaroot2:{
            type:String,
            default:''
        }
    },
    busTiming:{
        departureTime:{
            type:String,
            default:''
        },
        arrivalTime:{
            type:String,
            default:''
        },
    },
    busFeature:{
        noOfSeat:{
            type:Number,
            default:0
        },
        busType:{
            type:String,
            default:''
        },
        acType:{
            type:String,
            default:"Non-Ac"
        },
        multimediaType:{
            type:String,
            default:''
        }
    },
    busDescription:{
        type:String,
        default:''
    },
    busImages:{
        front_side:{
            type:String,
            default:null,
            required:true
        },
        left_side:{
            type:String,
            default:null,
            required:true
        },
        right_side:{
            type:String,
            default:null,
            required:true
        },
        back_side:{
            type:String,
            default:null,
            required:true
        },
        driver_cabin:{
            type:String,
            default:null,
            required:true
        },
        entire_inside:{
            type:String,
            default:null,
            required:true
        }
    },
    drivers:[
        {
            driverName:{
                type:String,
                default:''
            },
            driverMobile:{
                type:Number,
                default:''
            }
        }
    ],
    conductor:[
        {   conductorName:{
                type:String,
                default:''
            },
            conductorMobile:{
                type:Number,
                default:''
            }
        }
    ]
})

module.exports = mongoose.model("buses",busesSchema);